# Generated by Django 4.2 on 2023-04-18 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_image_user_profileimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profileimage',
            new_name='profile_image',
        ),
    ]
