# Generated by Django 4.2 on 2023-04-18 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_profileimage_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.URLField(max_length=400, validators=[django.core.validators.URLValidator()]),
        ),
    ]
