# Generated by Django 4.2 on 2023-04-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_range', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.CharField(max_length=10),
        ),
    ]
