# Generated by Django 4.2 on 2023-04-17 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatre_tips', to=settings.AUTH_USER_MODEL)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production', to='musicals.musical')),
            ],
        ),
    ]
