# Generated by Django 4.2 on 2023-04-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre_tips', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='tip',
            field=models.CharField(default='See this musical!'),
        ),
    ]
