# Generated by Django 4.2 on 2023-04-17 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('price_range', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('theatre', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('picture_1', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('picture_2', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('picture_3', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('video', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('website', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('genre', models.ManyToManyField(related_name='genre', to='genres.genre')),
                ('price_range', models.ManyToManyField(related_name='price', to='price_range.price')),
            ],
        ),
    ]
