# Generated by Django 4.2 on 2023-04-17 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musical',
            name='picture_1',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='musical',
            name='picture_2',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='musical',
            name='picture_3',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='musical',
            name='video',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='musical',
            name='website',
            field=models.URLField(max_length=500, validators=[django.core.validators.URLValidator()]),
        ),
    ]
